    language: java
    script:
          - ls
          - git clone https://github.com/makiyo5566/repo2.git
          - git clone git@github.com:makiyo5566/repo2.git
          - apt-get install ssh
    branches:  
        only:  
            - master  
    notifications:  
        email:  
             - chiayulu@iii.org.tw